Setup
ernestkorir/mathCal pull request #1
Opened 2023-03-20 18:02 UTC by ernestkorir

In this PR, I manage to:

1. Setup React using [Vite](https://vitejs.dev/guide/)
2. Setup Linters 

Thanks for reviewing this PR

2023-03-20 19:04 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @ernestkorir 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use Git Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-20 19:04 UTC, abdulhamiid commented on src/App.jsx
> +import './App.css';
When I opened your application, I encountered these errors 👇.

![image](https://user-images.githubusercontent.com/78251927/226438966-6ad1671e-75e0-414a-ab2f-cbea9051cef1.png)

Please kindly fix that 👍

2023-03-20 19:04 UTC, abdulhamiid commented on src/App.jsx
> +        </a>
Error in the `CONSOLE` 👇 

![image](https://user-images.githubusercontent.com/78251927/226439445-ecdfb5da-c4e1-4e7a-ae7d-322a6546f7e7.png)

Please let's make sure that app should run in the browser without errors 💪

2023-03-20 19:23 UTC, ernestkorir commented on src/App.jsx
> +        </a>
Thanks for this one
I had missed it out on my side but i have manage to fix it

2023-03-20 19:34 UTC, BregornOriginal approved these changes
## Hi @ernestkorir 

## Your project is complete!  There is nothing else to say other than... it's time to merge it 

## Congratulations! 

![giphy (2)](https://user-images.githubusercontent.com/93630700/226446850-b56b8fca-f8f7-46a4-88b7-c11ee3e603bb.gif)

## Highlights

✅ Good commit history
✅ Linters are passing
✅ Good work implementing vite

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-03-20 19:37 UTC, merged

2023-04-24 08:58 UTC, AlphaNtihinduka reviewed
# STATUS: APPROVED :green_circle: :clap: 
## Hi @ernestkorir 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover: